<?php
$additionalFormClass = (!CMA_AnswerThread::getMarkupBox()) ? 'no-markup-box' : '';
?>
<div class="cma-form-container cma-answer-form-container <?php echo $additionalFormClass ?>">
    <?php if(is_user_logged_in()): ?>
        <form method="post" class="cma-form">
            <input type="hidden" name="cma-thread" value="<?php echo $post->ID; ?>"/>
            <input type="hidden" name="cma-action" value="add" />

            <h3>
                <?php _e('Post your Answer', 'cm-answers-pro'); ?>
            </h3>

            <?php if(CMA_AnswerThread::getMarkupBox()) : ?>
                <ul class="cma-form-notes">
                    <li>
                        <?php _e('Allow markup', 'cm-answers-pro');
                        ?>: &lt;strong&gt;, &lt;em&gt;, &lt;a&gt;
                    </li>
                    <li>
                        <?php _e('Wrap your code using', 'cm-answers-pro');
                        ?> &lt;pre&gt;&lt;/pre&gt;
                    </li>
                </ul>
            <?php endif; ?>

            <?php
                $questionEditorContent = '';
                if(isset($populatedData['content']))
                {
                    $questionEditorContent = CMA_AnswerThread::getRichtextEditor() ? $populatedData['content'] : stripslashes(esc_html($populatedData['content']));
                }

            if(CMA_AnswerThread::getRichtextEditor())
            {
                wp_editor($questionEditorContent, 'answer-content-form', array('textarea_name' => 'content', 'textarea_rows' => 3));
            }
            else
            {
                ?>
                <textarea class="cma-form-content" cols="50" rows="3" name="content" placeholder="<?php _e('Write your Answer here', 'cm-answers-pro'); ?>"><?php echo $questionEditorContent; ?></textarea>
                <?php
            }
            ?>

            <div class="cma-form-options">
                <label class="cma-form-option-label">
                    <input name="thread_notify" type="checkbox" value="1"/>
                    <?php _e('Notify me of follow', 'cm-answers-pro'); ?>
                </label>
                <?php if(get_current_user_id() == $thread->getAuthorId()): ?>
                    <label class="cma-form-option-label">
                        <input name="thread_resolved" type="checkbox" value="1"/>
                        <?php _e('Mark as resolved', 'cm-answers-pro'); ?>
                    </label>
                <?php endif; ?>
            </div>

            <input type="submit" value="<?php _e('Post your Answer', 'cm-answers-pro'); ?>" />
        </form>
        <?php
    else:
        do_action('CMA_login_form');
    endif;
    ?>
</div>