<div class="cma-social-box">
    <div id="fb-root">
    </div>
    <div class="fb-like" data-href="<?php the_permalink() ?>" data-width="60" data-height="21" data-colorscheme="light" data-layout="button_count" data-action="like" data-show-faces="false" data-send="false"></div>
    <div class="g-plus" data-action="share" data-annotation="bubble"></div>
    <script type="in/share" data-counter="right"></script>&nbsp;
    <a href="http://twitter.com/share" class="twitter-share-button" data-url="<?php the_permalink() ?>" data-counturl="<?php the_permalink() ?>" data-text="<?php the_title(); ?>" data-via="username" data-related="username">Tweet</a>
</div>